# Generated by Django 4.0.6 on 2022-07-31 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('scrape_date', models.DateField()),
                ('file_size', models.FloatField()),
            ],
        ),
    ]
