# Generated by Django 4.0.6 on 2022-08-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='web_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.webpage'),
        ),
    ]
