# Generated by Django 4.0.6 on 2022-08-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagemetadata_web_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='image_url',
        ),
    ]
