# Generated by Django 4.0.6 on 2022-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_webpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
