# Generated by Django 4.0.6 on 2022-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagemetadata_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='width',
            field=models.IntegerField(),
        ),
    ]
